# Generated by Django 4.0.4 on 2022-05-28 18:25

from django.db import migrations


def default_user_admin(apps,schema_editor):
    user = apps.get_model('accounts',"AccountModel")
    user.objects.create_superuser(
        username='admin',
        password='1234',
        is_seller=True,
        is_admin=True,
        email='admin@mail.com'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(default_user_admin)
    ]
