# Generated by Django 4.0.4 on 2022-06-03 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('accounts', '0002_auto_20220528_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='stores.storemodel'),
        ),
    ]
