# Generated by Django 4.0.4 on 2022-06-03 03:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='variations', to='products.productmodel')),
            ],
            options={
                'verbose_name': 'variation',
                'verbose_name_plural': 'variations',
                'db_table': 'variations',
                'abstract': False,
            },
        ),
    ]
