# Generated by Django 4.0.4 on 2022-05-27 02:03

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('street', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('zip_code', models.CharField(max_length=9)),
                ('state', models.CharField(max_length=10)),
                ('other_information', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
