# Generated by Django 4.0.4 on 2022-06-03 03:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_value', models.FloatField()),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderVariationsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_value', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.ordersmodel')),
            ],
            options={
                'verbose_name': 'order_variation',
                'verbose_name_plural': 'orders_variations',
                'db_table': 'orders_variations',
                'abstract': False,
            },
        ),
    ]
