name: Django CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9.6, 3.9.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create Env
      run: |
            echo "TEST=True\nSECRET_KEY=django-insecure-x)aw&gz(3#cc4^7d1u+it@ri*mzo)zdo9tp4payx(4wt_&4bjq" > .env
            ls -a
            cat .env
    - name: Create Migrations
      run: python manage.py makemigrations
    - name: Run Tests
      run: python manage.py test -v 2
